/** Chaves dos blocos colapsáveis da guia Estratégia. Valor inicial: todos recolhidos. */
export const STRATEGY_DEFAULT_EXPANDED: Record<string, boolean> = {
    main_essencia: false,
    main_publico: false,
    main_comunicacao: false,
    brand_history: false,
    brand_values: false,
    brand_mission: false,
    brand_vision: false,
    main_services: false,
    differentiators: false,
    how_want_to_be_perceived: false,
    competitors: false,
    inspirations: false,
    audience_general: false,
    personas: false,
    tone_of_voice: false,
    words_that_fit: false,
    words_that_dont_fit: false,
    content_style: false,
    preferred_cta: false,
    avoid_in_communication: false,
    main_profile_objective: false,
    moment_objective: false,
    monthly_objective: false,
    strategy_notes: false,
    pillars: false,
};
